### ISSUE TITLE
ReadMe for Date encoding strategy

### ISSUE THREAD

**Issue by bagfatnick** [IBM-Swift/Swift-Kuery-ORM#115]
## Context and Description
Small error in Readme

`
    static var dateEncodingStrategy: DateEncodingFormat = .timestamp
`
should be:
`
    static var dateEncodingFormat: DateEncodingFormat = .timestamp
`

**Comment by kilnerm** [comment]
I have just merged a fix for this into master.

Thanks for catching this!!

Marking as closed. Please reopen you have any further follow up.
