### ISSUE TITLE
Model is not a great name for the 'marker' interface

### ISSUE THREAD

**Issue by gmosx** [IBM-Swift/Swift-Kuery-ORM#13]
The Ruby on Rails inspired name is a poor choice IMO. What about using something like `DBRecord`, `DBEntity`, `DBPersistable` or something similar?

**Comment by ianpartridge** [comment]
Thanks for the feedback. Can you explain why you think `Model` is a poor choice?

**Comment by gmosx** [comment]
Model reminds me of 'domain model' or MVC. I don't think you can find the term model in the database literature. The marker interface should denote that the specific  type (class/struct) can be stored in a database (not only stored, but also indexed, searched etc...) 

I think the terms Record/Entity are more common, and the `DB` prefix make the interface even more specific.

**Comment by EnriqueL8** [comment]
Hey @gmosx, I believe the term `Model` is widely used and accepted by the majority of the community. Also, I think for swift developers just getting started into persistence the idea of storing a `Model` is easier to grasp. Obviously we will keep this under review, and if the community continues to have concerns we would look to change it! Thanks for the concern
