### ISSUE TITLE
Using an existing field in the model as the Identifier

### ISSUE THREAD

**Issue by EnriqueL8** [IBM-Swift/Swift-Kuery-ORM#16]
At the moment, the ORM sets the primary key to be a auto incrementing Integer and it cannot be changed.
The idea is for example if we had:

```[swift]
stuct Book: Model {
  var name: String
  var author: String
  var releaseDate: Date
}
```

We would want the `name` to be the Identifier for Books.

An implementation would be to set a `static var` in the Model, which determines the id column.

```[swift]
extension Book {
  static var idColumn = "name"
}
```

This would default to a `id` column which is an auto incrementing integer.

**Comment by fobin** [comment]
Would also be nice if it would support other types of id's. First in mind comes uuid.

**Comment by EnriqueL8** [comment]
Hey @fobin, yes we have though about that instead of having to declare a field as UUID just change the type directly. Good shout!
