### ISSUE TITLE
Can't use save with id in completion closure 

### ISSUE THREAD

**Issue by eugeniobaglieri** [IBM-Swift/Swift-Kuery-ORM#37]
I have this struct:

```
public struct User: Codable {
    let name: String
    let username: String
    let password: String?
}

extension User: Model {}
```
If I try to save it, using this save method
```
/// Call to save a model to the database that accepts a completion
/// handler. The callback is passed an id, a model or an error
func save<I: Identifier>(using db: Database?, _ onCompletion: @escaping (I?, Self?, RequestError?) -> Void)
```
```
let u = User(name: "John", username: "Doe", password: "MySecret")
u.save(using: database) { (id, user, error) in
    NSLog("User saved with id: \(id)")
 }
```
I obtain this error, forcing me to use the other save variation:

<img width="979" alt="screenshot 2018-05-16 23 37 03" src="https://user-images.githubusercontent.com/1050414/40145443-15f0a2a2-5962-11e8-9b58-805dcf63d427.png">

What am I missing?

### Environment Details
macOS 10.13.04, Xcode 9.3.1, Swift 4.1

**Comment by eugeniobaglieri** [comment]
Try to remove id param from closure.
{ (user, error) in ...

**Comment by xeokeri** [comment]
> Try to remove id param from closure.
> { (user, error) in ...

I did that locally, but it seems that the ability to get the ID is lost.

**Comment by EnriqueL8** [comment]
In order for this closure to work, you will need to specify the type of the ID such as :

**Comment by kilnerm** [comment]
@eugeniobaglieri, @xeokeri, As noted by @EnriqueL8 in the previous comment you need to specify the types of the parameters passed into the completion handler. When you do this the desired API will be used. Let me know if you need any further help with this.

**Comment by kilnerm** [comment]
Marking this as closed, please reopen if you require further help!
