### ISSUE TITLE
Date not supported in SQLite

### ISSUE THREAD

**Issue by jeremyquinn** [IBM-Swift/Swift-Kuery-ORM#42]
## Context and Description
I have a simple Model containing some Swift Date properties.

When the struct is saved, I get an error: *Unsupported parameter type* in the function : `bind(parameter:at:statement:) -> QueryError?` in `SQLiteConnection`.

I tried adding a case for Date :
`case let value as Date: resultCode = sqlite3_bind_double(statement, index, Double(value.timeIntervalSinceReferenceDate))`

Which seemed fine for SQLite but it failed, I think, when it was read out and could not be converted back into a Date?

### Environment Details
MacOS 10.13.4
Xcode 9.4
Kitura 2.4.1
SwiftKuery 1.3.1
SwiftKueryORM 0.1.1
SwiftKuerySQLite 1.0.0

### Steps to Reproduce
Model struct contains a Date property 

    public struct Bookmark:Codable, Equatable {
        ...
        public var created: Date? // the creation date
        ...
    }

Route saves struct :

`router.post("/api/bookmarks/", handler: storeBookmark)`

    func storeBookmark(bookmark:Bookmark, completion: @escaping (Bookmark?, RequestError?) -> Void ) {
        bookmark.save(completion)
    }

**Comment by jeremyquinn** [comment]
BTW. The same problem with enums (RawRepresentable) even though it is Int, Codable etc., fails to bind.

**Comment by ianpartridge** [comment]
Hi @kilnerm can you take a look please?

**Comment by jeremyquinn** [comment]
In `CodableRouter` in `httpStatusCode(from error: RequestError) -> HTTPStatusCode` I added `Log.debug("mapping error to 500: \(error.reason)")`.
Now I see `mapping error to 500: Unsupported type: Date for value: Optional(549748721.94289601)` which I guess confirms my fix above is incomplete.

**Comment by jeremyquinn** [comment]
I guess this change should be happening in DatabaseDecoder, DatabaseEncoder.

**Comment by jeremyquinn** [comment]
I have fixes for Date and Date? for DatabaseDecoder and DatabaseEncoder, if you are interested.

**Comment by EnriqueL8** [comment]
Hey @jeremyquinn, if you could raise a PR with the fixed that would be great!
