### ISSUE TITLE
Kuery-ORM (0.1.1) seems to be adding a character to some table names

### ISSUE THREAD

**Issue by fwgreen** [IBM-Swift/Swift-Kuery-ORM#50]
I have an existing table called `availability` on PostgreSQL
```sql
CREATE TABLE public.availability
(
  id bigint NOT NULL DEFAULT nextval('availability_id_seq'::regclass),
  starting timestamp with time zone,
  ending timestamp with time zone,
  overtime boolean,
  on_shift boolean,
  CONSTRAINT pk_availability PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE public.availability
  OWNER TO postgres;
```
Here's my model
```swift
struct Availability : Codable {

    var id: Int
    var starting: Date
    var ending: Date
    var onShift: Bool
    var overtime: Bool
}

extension Availability : Model {}
```
This is the error message from the database server
```
ERROR:  relation "availabilitys" does not exist at character 15
STATEMENT:  SELECT * FROM Availabilitys
```
Oddly, it does not do this with all entity names.  It would be great if one could specify table and column names, JPA style: `let tableName = "whatever_name"` is completely ignored.

**Comment by EnriqueL8** [comment]
Hey @fwgreen , I have realised that for the custom column names you can just use CodingKeys, like so:
```
extension Availability: Model {
    enum ColumnKeys: String, CodingKey {
      case id, starting, ending, overtime
      case onShift = "on_shift"
   }
}
```

**Comment by fwgreen** [comment]
@EnriqueL8 This is a potentially elegant solution, that at the moment doesn't work:  I only have one table without a snake-cased column name and it's the only one that Kuery-ORM can retrieve.  Everything else triggers an empty 500 error which isn't caught by the logger, but instead is only seen in my REST client.

PS: While `tableName` got rid of the original SQL error on the database server, there is still the underlying issue of the magical "s" being appended to some names.

**Comment by EnriqueL8** [comment]
Hey @fwgreen, the magical "s" is appended by default to the table names.
For the column names, I made a mistake instead of `ColumnKeys` is had to be `CodingKeys`
Like so,

**Comment by fwgreen** [comment]
Thanks for putting me on the right path!

**Comment by Beautylivery** [comment]
Hello, i am quite new user to this project however, i believe an s behind every table just randomly need to be fixed, as this is a bug in the code. Right ?

Clearly its fine that struct name = table name but not struct name = table name + s . Especially working with existing tables like me this gives a whole lot of a mess.

The here presented solution is simply a work around on an issue that still seems to exist.

My example: I try to read out from a table: wp_amelia_providers_to_daysoff ... and i can simply not do it. unless i probably apply the work around which i will now try to do.

But i would still looking forward that the magical s bug is fixed.
By the way i am using now:
Swift Kuery: 3.0.1
Swift ORM: 0.6.0
SwiftKueryMySQL 2.0.2

**Comment by fwgreen** [comment]
@Beautylivery The problem is this is a deliberate design choice and not a bug.  The architects have assumed that all users are English speakers and all English nouns are pluralized by adding an "S".  Feel free to open a new issue.
