### ISSUE TITLE
TINYINT (8-bit integer) datatype is not supported

### ISSUE THREAD

**Issue by spykr** [IBM-Swift/Swift-Kuery-ORM#74]
## Context and Description
Trying to decode a TINYINT datatype will throw an error, whether you try to decode to `Int` or `Int8`. This is frustrating as I believe it's common practice to use TINYINT to represent boolean values. 

### Steps to Reproduce
1) Use the TINYINT datatype in a MySQL table 
2) Attempt to use the corresponding Kuery model, with the type of the field set to either `Int` or `Int8`
3) Either one will fail

### Solution
After inspecting DatabaseDecoder it seems this is caused by a missing line in the Int decoder:

```swift
/// Special case for integer, no integer type in database
public func decode(_ type: Int.Type, forKey key: Key) throws -> Int {
    let unwrappedValue = try unwrapValue(key, checkValueExitence(key))
    let returnValue: Int
    switch(unwrappedValue) {
    case let v as Int16: returnValue = Int(v)
    case let v as Int32: returnValue = Int(v)
    case let v as Int64: returnValue = Int(v)
    default:
    throw DecodingError.typeMismatch(type, DecodingError.Context(
        codingPath: [key],
        debugDescription: "Could not convert " + String(describing: unwrappedValue)
    ))
    }
    return returnValue
}
```

If the switch also included:

```swift
case let v as Int8: returnValue = Int(v)
```

then TINYINT would be correctly decoded. I confirmed this by changing my local copy of the file and testing it.

(P.S. It would also be really handy if there was a way to directly decode TINYINT to a boolean without implementing a custom decoder)

**Comment by xeokeri** [comment]
Don't forget the following:

```swift
public func decodeIfPresent(_ type: Int.Type, forKey key: Key) throws -> Int? {
    let value = try checkValueExitence(key)
    if value == nil { return nil}
    let returnValue: Int
    switch(value){
    case let v as Int8:  returnValue = Int(v)
    case let v as Int16: returnValue = Int(v)
    case let v as Int32: returnValue = Int(v)
    case let v as Int64: returnValue = Int(v)
    default:
        throw DecodingError.typeMismatch(type, DecodingError.Context(
            codingPath: [key],
            debugDescription: "Could not convert " + String(describing: value)
        ))
    }
    return returnValue
}
```

And additionally, in SwiftKuery, it is missing this:

```swift
extension Int8: SQLDataType {
    /// Return database specific representation of the int8 type using `QueryBuilder`.
    ///
    /// - Parameter queryBuilder: The QueryBuilder to use.
    /// - Returns: A String representation of the type.
    public static func create(queryBuilder: QueryBuilder) -> String {
        return "tinyint"
    }
}
```

Which would then allow using the following:

```swift
public struct RandomNameHere : Codable {
    public var id: Int
    public var randomColumnNameHere: Int8
}

extension RandomNameHere : Model {

}
```

**Comment by kilnerm** [comment]
@spykr, @xeokeri, Unfortunately we cannot add support for the TINYINT type. While MySQL and SQLite both support 1 byte integers PostgreSQL does not and as such we cannot add support in an abstract fashion for the type.

I considered whether we could do some special handling for PostgreSQL and store TINYINT values as a char but this leads to other issue such as someone storing an actual char in the table directly. Equally, storing as a larger integer type and then casting down has potential problems with value wrapping if a value greater than Int8's maximum is directly inserted into the table.
