### ISSUE TITLE
Support for PostgreSQL schemas broken

### ISSUE THREAD

**Issue by fwgreen** [IBM-Swift/Swift-Kuery-ORM#84]
I updated an old project and found that Kuery-ORM no longer recognizes PostgreSQL schemas:

```Swift
struct Person : Codable, Model {
    static var tableName: String = "folks.person" //folks is the schema and person the table
    
    var id: Int 
    var firstName: String 
    var lastName: String 
    var jobTitle: String

    enum CodingKeys : String, CodingKey {
        case id
        case firstName = "first_name"
        case lastName = "last_name"
        case jobTitle = "job_title"
    }
}
```
```
Error:  706 : Query execution error:
ERROR:  relation "folks.person" does not exist
LINE 1: SELECT * FROM "folks.person"
                      ^
 For query: SELECT * FROM "folks.person"
```

**Comment by kilnerm** [comment]
This is an unexpected consequence of the changes we made to support case sensitivity in the database plugins. I can recreate the issue outside Kuery by simply creating a schema, creating a table within it and then wrapping the `schema.tablename` in double quotes in a `SELECT` statement.

This one may be tricky to fix in an elegant fashion, will see what I can come up with.

**Comment by kilnerm** [comment]
Having spent some time looking at this issue in more depth I have concluded schema's are not something that we can support or that were intentionally supported in the past.

My reasoning for this is the fact that the three supported databases for SwiftKuery all have different implementations of SCHEMA that we are not able to implement support for in a plugin agnostic manner. While an implementation could be made it would result in application code that was not portable between database plugins which would be contradictory to SwiftKuery being an abstraction of the underlying plugin implementations.

@fwgreen, unfortunately this is not something we will be able to resolve. It is possible to use raw queries to interact with schema's via the executeQuery methods on a model but the utility functions such as save and find will not work.

**Comment by fwgreen** [comment]
@kilnerm I'm sorry to hear that.  I had assumed that the support for PostgreSQL came from its [Swift-Kuery plugin](https://github.com/IBM-Swift/Swift-Kuery-PostgreSQL/issues/2) and not from Swift-Kuery or Swift-Kuery-ORM.  

Adding the ability to perform a raw query as part of the database configuration, while not elegant, would mostly solve the problem:  The user could then set the `search_path` for the rest of the session.

**Comment by kilnerm** [comment]
I'm marking this as closed. If anything changes with regard to our ability to implement a solution we can re-open.
