### ISSUE TITLE
([SwiftKuery.Column]) columns = <Unable to determine byte size.>

### ISSUE THREAD

**Issue by mbmshafraz** [IBM-Swift/Swift-Kuery-ORM#98]
## Context and Description
A description of the issue.

### Environment Details
Development Envirement MacOS, MySQL server on Ubuntu, Swift 4.2 and Xcode 10.1.

### Steps to Reproduce
Save an object using save function

### Expected vs. Actual Behaviour
receiving ([SwiftKuery.Column]) columns = <Unable to determine byte size.>

**Comment by kilnerm** [comment]
@mbmshafraz, can you add your table definition and code calling the save (including values) to the issue please?

**Comment by kilnerm** [comment]
I discussed the issue on slack, the root of the problem was that a pre-existing database table had an incorrect name for the model:
```swift
struct Visitor: Model {
   var email: String = “test@mail.com”
   var receiveMail = 0
}
```

The error message should be better in these circumstances so I will use this issue to improve it!

**Comment by kilnerm** [comment]
I'v not been able to recreate this error, I asked the originator for further assistance on Slack.

**Comment by kilnerm** [comment]
Marking this as closed. Should further information become available I will re-open.
